### ISSUE TITLE
Installation process for Au-CLI is abhorrently complicated / doesn't work?

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [aurelia-ui-toolkits/aurelia-materialize-bridge#446] opened 2017-06-30 09:59 UTC
Shame on you guys for making this tool nearly impossible to install.   You absolutely positively must include drillable documentation that will explain everything to those who are somewhere below expert status.

I'm using Au CLI 30.0 -- with Systemjs.    No mention at all about this version of the CLI in your docs.  

It upsets me to put an hour or so into the study of your process to find out late in the game that there are one or more things that don't work (Fonts?).... can't you put that on top of your install process so people like me won't waste their time when they discover at some point that enough things "don't work"?

**Comment by swalters** [comment] 2017-06-30 16:57
Strong language for an open source project where all the contributors are volunteers. You spend your holiday or weekend making the needed docs or making sure that the project works with each and every release of the CLI for no pay and then see how strongly you feel.   I've participated in open source projects and comments like this eat the soul of OSS.  

I for one am super grateful for the abundance of documentation that IS there and reflect on how many hours someone spent to make them.

You could have raised the issue in a constructive manner.

**Comment by adriatic** [comment] 2017-06-30 17:25
Thank you @swalters for your comments, as they help to prevent our soul from being eaten :-)

**Comment by SolidStateLEDLighting** [comment] 2017-07-01 02:02
The installation process should absolutely be the easiest thing your software does.    And if it is not easy, then it needs to be explained in extraordinary detail so a user can understand all the ramifications of the install - with debugging hints at every step.

Is the volunteer world of software projects always like this?   Where developers are temperamental?

You can secure your soul by getting things done well -- and if you can't support every release of the CLI -- then so be it.

Get a commitment from the Au CLI people to provide you the right tools so you can get the installation nailed down solid -- and don't release the product until it's ready for prime time.  That will energize your soul.

**Comment by vegarringdal** [comment] 2017-07-01 14:17
@SolidStateLEDLighting 

>Shame on you guys for making this tool nearly impossible to install. You absolutely positively must include drillable documentation that will explain everything to those who are somewhere below expert status.

Hmm, not a good way to start asking for help..

>It upsets me to put an hour or so into the study of your process to find out late in the game that there are one or more things that don't work (Fonts?).... can't you put that on top of your install process so people like me won't waste their time when they discover at some point that enough things "don't work"?


> "dont work", "study of your process to find out late"

What dont work?
Did you study/read the cli install section before you started doing anything?
Are you saying that the "handling of fonts" part does not work ?
The one here? 
https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/aurelia-cli.html

If you want the creator of this awesome bridge/or other users to be helpful, then you need to learn to explain what the issue is in detail, where it fails, what errors did you gets.
If its some parts you think can get better, explain what you think is missing, or what would help you better understand
If there is parts you dont understand, then copy parts out and ask questions (do not copy all!!!!)

Thanks for reporting issue, but please try again with a little more effort and details so @Thanood or others can be more helpful when they have time.

👍 😄

**Comment by djensen47** [comment] 2017-07-01 22:51
@SolidStateLEDLighting 

This particular project is one of the best communities and one of the best maintained projects I have been lucky to be a small part of. @Thanood is super responsive, he takes pull requests, he's open to suggestions, and he keeps this project **up to date**.

From my experience:
1. I was able to install on the first try.
2. The documentation has a section about the font situation.
3. Part of the installation "issue" is out of scope from _this_ project which depends on at least two other projects: 
- Dogfalo/materialize is not AMD nor commonjs compatible 
- aurelia/cli itself is not version 30.0, it is currently version `0.30.1` that's pre 1.0 and they're still making improvements to make things easier.
4. Instead of spending an hour and alienating everybody, just ask. You don't even have to be very polite, just don't be a jerk about it. **This community and @Thanood are super helpful**. If you just ask for help or point out where you ran into issues, then you will get an answer and fairly quickly compared to most open source projects.
5. The developers here are not temperamental. They're actually quite helpful and friendly. But that's beside the point because none of the core "developers" on this project have commented here. We're all users or occasional contributors to the project.

**Comment by Thanood** [comment] 2017-07-02 15:41
Thanks everyone for your kind words.. 😃 

I agree with one point: the documentation may not be the best of the world. It can be improved, probably a lot.

Tbh, I just don't agree with the rant.

The font section has been added (https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/284) some time ago. After some **constructive** criticism from users, btw.

It's not easy to "judge" my own written documentation since *I* know the obstacles well enough to "steer" around them. So any input is - in fact - appreciated.
Even better if that input tells me what's wrong. 😏 

I'm just seeing "the font section is hard to find" and "systemjs is not mentioned".

> Is the volunteer world of software projects always like this?

Just because you ask: yes, it is. Every volunteer project anywhere in the world exists only if people *volunteer* to be of any help. Any volunteer can only put so many hours of her/his life into any project.

Personally, I think the open source voluntary community is very interesting *because* they open projects to the public *before* they are finished (in a professional sense of the word). That's actually the cool thing about it. And if I care enough about a project I can raise my voice and *improve* the project with some features I want to see. That's completely impossible in a closed-source environment.

**Closed** 2017-07-04 13:40 UTC

**Comment by Thanood** [comment] 2017-07-04 13:46
Restarting the conversation here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/447
