### ISSUE TITLE
Using with new aurelia easywebpack from typescript-webpack skeleton?

### ISSUE THREAD

**Issue by abeven** [aurelia-ui-toolkits/aurelia-materialize-bridge#225] opened 2016-08-04 05:41 UTC
Getting all sorts of "Cannot find module aurelia-materialize-bridge" errors in my "import {...} from 'aurelia-materialize-bridge" statements when migrating from AureliaWebpackPlugin. I was able to run the bridge fine before Aurelia 1.0.0 by using the "includeSubmodules" option, but now that's been deprecated. I've tried 
"aurelia": {
    "build": {
      "resources": ["aurelia-materialize-bridge"]
    }
  }

but to no avail. 

Has anyone else run into this? How'd they get it working? Great, great project btw!

**Comment by Thanood** [comment] 2016-08-04 06:16
Does this help in any way? https://github.com/Thanood/md-webpack-skeleton

It's using RC1, not 1.0 - will have to check that out again. And it's not TypeScript. But it's also not using `includeSubmodules`.

If it's only for typings, these should be here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/dist/aurelia-materialize-bridge.d.ts (or `node_modules/aurelia-materialize-bridge/aurelia-materialize-bridge.d.ts`).

It should be available with using `typings` I guess. If nothing works, try to copy the file into `custom_typings` to see if the file itself is wrong somehow.

Would you mind having a quick look at the `.d.ts` file and tell me if it's generated correctly? I must say I'm a little confused about all the `export declare class` - TS docs tell me that this is correct but I've never seen that before.

**Comment by Thanood** [comment] 2016-08-10 08:58
@abeven Any news on this?

I will have to explain where users should get typings from.

**Comment by Ullfis** [comment] 2016-08-10 13:13
I wont guarantee for any or this. But got it running without compile errors.

Clone and npm install skeleton-typescript-webpack

```
npm rm bootstrap --save
npm rm jquery --save
npm rm @easy-webpack/config-global-jquery --save-dev
npm i jquery@2.2.4 --save
npm i materialize-css --save
npm i aurelia-materialize-bridge --save

npm i script-loader –save-dev
```
I use script-loader to get jquery and materialize global (not ideal solution).

#### webpack.config.js:

remove (line 89/125/152): 
```
require('@easy-webpack/config-global-jquery')(), 
```

```
coreBundles  = {… ,
  materialize: [
    'jquery',
    'materialize-css/dist/js/materialize.min.js',
    'aurelia-materialize-bridge'
  ];

…

const baseConfig = {
  entry: {
    'app': [/* this is filled by the aurelia-webpack-plugin */],
    'aurelia-bootstrap': coreBundles.bootstrap,
    'aurelia': coreBundles.aurelia.filter(pkg => coreBundles.bootstrap.indexOf(pkg) === -1),
    'materialize': coreBundles.materialize
  },
  output: {
    path: outDir,
  },
  module: {
    loaders: [
      {
        test: /[\/\\]node_modules[\/\\]jquery[\/\\]dist[\/\\]jquery\.js$/,
        loader: "script"
      },
      {
        test: /[\/\\]node_modules[\/\\]materialize-css[\/\\]dist[\/\\]js[\/\\]materialize.min\.js$/,
        loader: "script"
      }
    ]
  }
}

```

#### src/main.ts:

remove
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap';

add
import 'materialize-css/dist/css/materialize.min.css';

and
.feature('aurelia-materialize-bridge', b => b.useAll());


#### package.json

```
  "aurelia": {
    "resources": [
      "aurelia-materialize-bridge"
    ]
  },
```

#### node_modules/aurelia-materialize-bridge/package.json

add these resources

```
    "build": {
      "resources": [
	"aurelia-materialize-bridge/index",
	"aurelia-materialize-bridge/autocomplete/autocomplete",
	"aurelia-materialize-bridge/chip/chips",
```


#### npm start

I use Atom and had to change tsconfig.json to skip errors in editor. Changed “es2015” to “es6” and added “outDir”: “.tsbuild” to remove compiled js and map files in src folder. I dont know if you need to do that.

```
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "allowJs": true,
    "outDir": ".tsbuild"
  },
```

I have not tested all components in the bridge.

**Comment by Thanood** [comment] 2016-08-10 13:43
Wow, thanks!
So it's not just missing typings? I ask because webpack-esnext is pretty easy to do.

**Comment by Ullfis** [comment] 2016-08-10 14:04
No problem with missing typings here. Needed to add 3 lines to bridge package before it would build.

I got some trouble with md-waves effect using ts-webpack and this solution. Wave is not removed on button after pressing it (not tested more yet). Do you have a webpack-esnext project I can study to see if the webpack-ts can be configured another way?

**Comment by Thanood** [comment] 2016-08-10 14:16
It's not updated to Aurelia 1.0 but here it is: https://github.com/Thanood/md-webpack-skeleton

**Comment by Ullfis** [comment] 2016-08-10 14:38
Installed.. :smile:

I needed to add 

```
"aurelia-materialize-bridge/autocomplete/autocomplete",
"aurelia-materialize-bridge/chip/chips",
```
 under

```
"build": {
      "resources": [
```
in package.json to get it to build.

Same trouble with waves.

Going to try out with latest aurelia components.

**Comment by Thanood** [comment] 2016-08-10 14:44
Interesting since in my tests I didn't need this. It's all in the bridge's `package.json`..
Oh, right... That was before I've added autocomplete and chips.. Doh! :smile: 

[Waves should be in, though](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L184)

**Comment by Ullfis** [comment] 2016-08-10 14:52
Yeah… hehe. Waves is there and trigger when pressing a button with md-waves attribute. But the button wont get “back to start”. If the effect trigger a darker wave, the button get darker and darker every time its pressed.

Maybe its something strange on my computer. Wave on jspm version work.

**Comment by Thanood** [comment] 2016-08-10 15:11
It's not your computer. I've noticed this, too but I thought it was solved with the latest Aurelia/webpack versions.
Apparently it's not.

**Comment by Thanood** [comment] 2016-08-10 15:15
Actually what I thought was: Materialize may be initialized twice ([which has really been the case with webpack](https://github.com/aurelia/skeleton-navigation/issues/564)).

That particular issue is solved now with the 1.0.0 **skeleton**. My skeleton is pre-1.0.0 and that may be the issue because in my tests for the above mentioned issue it was not enough to just update webpack dependencies.

Something in the config must be different.

**Comment by Ullfis** [comment] 2016-08-10 16:31
[webpack-esnext working](https://github.com/Ullfis/aurelia-materialize-skeleton-esnext-webpack) with [this commit](https://github.com/Ullfis/aurelia-materialize-skeleton-esnext-webpack/commit/c368d9c762e541ce40f42fa76c47fe5b9920320e)

going to do the same with typescript.. a sec

**Comment by Thanood** [comment] 2016-08-10 18:07
Thanks for testing! :smile: 
I hope closing this was okay. Seems to work..

**Comment by Ullfis** [comment] 2016-08-12 07:25
Duh.. build:prod and server:prod didn't work. I just got «TypeError: a is not a function» in the browser console.

I needed to copy the build from easy-webpack/config-uglify and change mangle.keep_fnames to false to get it working. Don't know if it will destroy other stuff. But with this skeleton it work.

I have updated the webpack-typescript repository.

**Comment by Thanood** [comment] 2016-08-12 08:01
@Ullfis there is a note in installaton description:

> When using aurelia-materialize-bridge (and thus materialize) via webpack with the UglifyJS-plugin (standard in aurelia webpack skeleton production build) you have to make sure to except the materialize module (via exclude: ['materialize'] if your module is named materialize) from the UglifyJS plugin. Otherwise the names will be mangled and the materialize module won't load correctly (missing dropdown). Another option would be to disable mangle as a global setting on the UglifyJS settings object.

It's suggesting to set mangle to `false` but your description seems more appropriate.
I'm reopening this to remind myself to test this and change the documentation.

**Comment by Ullfis** [comment] 2016-08-12 08:10
I did try with exclude: ["materialize-css"] without luck. Just link. I will (try to) not change them :smile:

**Comment by Thanood** [comment] 2016-08-12 08:17
Maybe it's good if you change them (f.i. for fixes like the one you did above) :wink: 
But I can also fork them, no problem. That way, I'm up to date if something changes.

Thinking about it, I'll have to (kind of) recreate them anyway. I like to test (aka "do it myself") anything I put in the docs.

**Comment by Ullfis** [comment] 2016-08-12 09:35
I just use different branches like this one [aurelia-materialize-skeleton-i18n-typescript-webpack](https://github.com/Ullfis/aurelia-materialize-skeleton-typescript-webpack/tree/aurelia-i18n). It's just for testing anyway. Fork if you want to be safe lol.

**Comment by Thanood** [comment] 2016-09-07 19:07
Wow, this is still open? Shame on me..

I'll try to reproduce the steps tomorrow and update the documentation.
Also, i'll put the installation instructions into the GitBook so I don't have to deploy the sample app everytime I fix something in the docs..

**Closed** 2016-09-21 17:34 UTC
Labels: needs documentation

**Comment by smithaitufe** [comment] 2017-02-07 22:22
@Ullfis Thanks for the practical solution. It worked for me.
