### ISSUE TITLE
Add missing steps to the installing guide (Documentation)

### ISSUE THREAD

**Issue by leonardocaldas** [aurelia-ui-toolkits/aurelia-materialize-bridge#204] opened 2016-07-06 20:49 UTC
I followed the installing guide steps [http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation](http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation), and after hours trying to get the components working, i found out that i needed to run:

    jspm install npm:materialize-css

And after that, i had to manually add the map of 'materialize' to the config.js file.

In the docs, it says to add

    import 'materialize';

to the beginning of the main.js file, but it does not explain how to install the dependencies to make the code above works.

Could you guys update the documentation to go through all the steps needed in order to make everything  works?

**Comment by Thanood** [comment] 2016-07-06 21:25
That's strange since the bridge has a jspm dependency on `github:Dogfalo/Materialize`. That's what you probably should have installed (`jspm install materialize`).

Can you tell me when you tried that? Because a few hours ago I published a version that may have caused that. Could well be that the documentation is off after that change.

**Comment by leonardocaldas** [comment] 2016-07-06 22:38
I tried it today, i started in the morning and only made it work by afternoon.

I executed the command below
    jspm install aurelia-materialize-bridge

and i tried to executed
    jspm install

to see if there was any dependency not installed, but it did not work, and that was when i thought of trying to install the materialize manually, and for my surprise it worked.

**Comment by leonardocaldas** [comment] 2016-07-06 22:46
I just checked my config.js file, and the dependency you mentioned is there

```javascript
    "github:Dogfalo/materialize@0.97.6": {
        "css": "github:systemjs/plugin-css@0.1.23",
        "jquery": "npm:jquery@3.0.0"
    },
```

but this alone did not make the ```import 'materialize';``` works.

**Comment by Thanood** [comment] 2016-07-07 09:09
Apologies that this took so much of your time.

There are two reasons I could think of:
* jspm installed jQuery 3, although it should have downgraded as the bridge is configured to pull jQuery 2 - in that case `jspm update` should probably help
* Dogalo/Materialize is not available as a top-level dependency after installation

Could also be both. :smile: 
Also both should be mentioned in the documentation. I will add that to the docs.

Can you try that?
* uninstall `materialize-css` and remove the map
* `jspm install materialize`
* (optional) check jQuery version, should be < 3

Also it would be interesting to know if there are or have been any errors before you installed `materialize-css`.

**Comment by leonardocaldas** [comment] 2016-07-07 11:49
Hi Thanood,

I did what you suggested, i installed everything again and before running ```jspm install aurelia-materialize-bridge```, i ran ```jspm install materialize```, and you were right, this command solved the ```import 'materialize';``` problem, but still didnt work.

When i tried to use one of the available components(collapsible), an error occurred:

```javascript
collapsible.js:47 Uncaught (in promise) TypeError: $(...).collapsible is not a function
    at MdCollapsible.refresh (http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.10.0/collapsible/collapsible.js:47:23)
    at MdCollapsible.attached (http://localhost:9000/jspm_packages/npm/aurelia-materialize-bridge@0.10.0/collapsible/collapsible.js:31:12)
    at Controller.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:3409:24)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1533:24)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1887:15)
    at View.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1538:21)
    at ViewSlot.attached (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-rc.1.0.0/aurelia-templating.js:1887:15)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-framework@1.0.0-rc.1.0.1/aurelia-framework.js:208:30)
```

After that, i tried ```jspm update``` as you mentioned, and you were right again, it was using the version  3.0.0 of jquery, and the update downgraded it to the v2.2.4, but even with that, the problem persisted.

Let me show to your all the steps i made to get to this point:

1. Download the production setup skeleton
2. Use the ESNext build
3. Run ```npm install```
4. Run ```jspm install -y```
5. Run ```jspm install materialize```
6. Run ```jspm install aurelia-materialize-bridge```
7. Update the main.js file to load the materialize bridge
8. Try to use any of the components (will get an error)
9. Run ```jspm update```
10. Try to run it again (will get the error ```collapsible.js:47 Uncaught (in promise) TypeError: $(...).collapsible is not a function```)

Hope this can help you to understand whats happening...

Any ideas?

**Comment by Thanood** [comment] 2016-07-07 17:55
@leonardocaldas Unfortunately I'm on vacation for a week now but I'll reach out to the other team members to try to help.
Please also see if this issue is relevant: https://github.com/aurelia/skeleton-navigation/issues/557

**Comment by JeroenVinke** [comment] 2016-07-07 18:20
@leonardocaldas All right, just tried this myself and I can confirm that it doesn't work as planned. Materialize is installed but only as a second level dependency (while a top level dependency is needed for jspm to be able to import it via `import 'materialize'`).

Instead of installing materialize via `jspm install materialize`, use this instead: `jspm install materialize=github:Dogfalo/materialize`. This ensures that the correct materialize is used and installed under the alias "materialize". 

Also, confirm that you are on JSPM 0.16.15 (jspm -v) since we have had issues with other issues in the past. 

So the steps are:

1. Download and extract esnext of [aurelia-skeleton-navigation(https://github.com/aurelia/skeleton-navigation)
2. Run npm install
3. Run jspm install -y
4. Run jspm install materialize=github:Dogfalo/materialize
5. Run jspm install aurelia-materialize-bridge
6. run jspm update (so that jspm resolves potential version conflicts with jquery)
7. Update the main.js file to load the materialize bridge
8.Try to use any of the components

A sample repository can be found here: https://github.com/JeroenVinke/materialize-bridge-install

**Comment by leonardocaldas** [comment] 2016-07-07 23:23
@JeroenVinke thanks!!

Now it worked just fine.  When possible, try to to add some of these informations to the bridge documentation, it would be very helpful.

**Comment by JeroenVinke** [comment] 2016-07-08 05:38
Will do, glad that it works :)

**Comment by Thanood** [comment] 2016-07-10 07:27
Thanks for helping out, @JeroenVinke.
I wonder what is installed with `jspm install materialize` now. Maybe a change in jspm registry?

**Comment by Thanood** [comment] 2016-07-13 18:01
Will be fixed with today's catalog update.

**Closed by Thanood** 2016-07-13 18:01 UTC
Labels: wants documentation

**Comment by victormaestri** [comment] 2016-09-06 14:29
> @leonardocaldas All right, just tried this myself and I can confirm that it doesn't work as planned. Materialize is installed but only as a second level dependency (while a top level dependency is needed for jspm to be able to import it via import 'materialize').
> 
> Instead of installing materialize via jspm install materialize, use this instead: jspm install materialize=github:Dogfalo/materialize. This ensures that the correct materialize is used and installed under the alias "materialize".
> 
> Also, confirm that you are on JSPM 0.16.15 (jspm -v) since we have had issues with other issues in the past.
> 
> So the steps are:
> 
> Download and extract esnext of [aurelia-skeleton-navigation(https://github.com/aurelia/skeleton-navigation)
> Run npm install
> Run jspm install -y
> Run jspm install materialize=github:Dogfalo/materialize
> Run jspm install aurelia-materialize-bridge
> run jspm update (so that jspm resolves potential version conflicts with jquery)
> Update the main.js file to load the materialize bridge
> Try to use any of the components
> A sample repository can be found here: https://github.com/JeroenVinke/materialize-bridge-install

Hello,

I follow all the instructions, but I still have a error in my project:

```
GET http://localhost:9000/dist/aurelia-pal.js 404 (Not Found) - system.src.js:1056

Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/aurelia-pal.js(…) - system.js:4
```

I don't know why, jspm install all dependency include aurelia-pal.

Anyone can help me?

**Comment by Thanood** [comment] 2016-09-06 14:54
@victormaestri Is this based on the skeleton you quoted or did you do it from scratch?

**Comment by victormaestri** [comment] 2016-09-06 15:06
Yes @Thanood , I am used Esnext from aurelia-skeleton. Before I did tried with aurelia-cli, but I had another problems, so I decided try with aurelia-skeleton.

**Comment by Thanood** [comment] 2016-09-06 15:17
Dis you run `jspm update`?
For a quick fix try  `jspm install aurelia-pal` but I suppose this should be pulled by Aurelia skeleton already.

Anyway, I wonder why this happens.

**Comment by Thanood** [comment] 2016-09-06 15:55
I just took a completely new download of the esnext skeleton (from their "releases" tab) and installed materialize and the bridge. I can reproduce this issue.

We may have an unnecessary dependency on `aurelia-pal` which is missing in the skeleton. I'd like to check this out.

Did my "quick fix" work, btw? :smile: 

Please continue discussion in a new issue: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/204#issuecomment-244968036

Since this issue is closed and the original issue has been about something completely different. :smile:
