### ISSUE TITLE
New webpack skeleton not working with AMB

### ISSUE THREAD

**Issue by eikaramba** [aurelia-ui-toolkits/aurelia-materialize-bridge#401] opened 2017-04-10 15:36 UTC
Just wanted to create a ticket that the new skeleton is not yet working with AMB out of the box. 

Needed to add

```
ModuleDependenciesPlugin({
      "aurelia-materialize-bridge": [
'./autocomplete/autocomplete',
'./badge/badge',
'./box/box',
'./breadcrumbs/breadcrumbs',
.... and so on
```

However even with that lot of files are missing it seems (e.g. slider.css). I'm still trying to figure this out, but maybe it would be nice if AMB is supporting this Platform implementation in the future, so that dependencies will be resolved automatically.
https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies

**Comment by Thanood** [comment] 2017-04-10 18:10
Thanks. 👍 

Strange, I was sure that I've read somewhere that the build resources config should still be supported by the new webpack and [we've done that](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/package.json#L192-L242).

But I'll need to refresh my knowledge and read through their wiki.

**Comment by eikaramba** [comment] 2017-04-10 21:26
Yes exactly that is also my understanding, although i have to admit i'm not the biggest webpack expert. ;)

BTW: Currently my problem is that even with the manual addition of the dependencies above i get an error:

`Failed loading required CSS file: aurelia-materialize-bridge/slider/slider.css`

This is because the slider component does not have a html file that is requiring the css. I did not see how the js file is requiring the css, so..... mhmmmm well it is missing. Unfortunately adding the css file to the dependency list does not work (i guess you can only add js and html).

**Comment by Thanood** [comment] 2017-04-11 07:45
Related: https://github.com/aurelia/webpack-plugin/issues/104

**Comment by eikaramba** [comment] 2017-04-11 11:59
As mentioned above it seems one need to use a html template instead of the inlineView decorator for the slider component, so that the webpack plugin can "discover" this dependency of the css file itself. That said, i already tried that and unfortunately it did not work yet. Will continue to see where the problem is, but for now i'm kind of stuck it seems. So waiting on your experience with it to confirm this problem ....

**Comment by eikaramba** [comment] 2017-04-11 12:00
Ha, there is already a ticket for this :) https://github.com/aurelia/webpack-plugin/issues/101

**Comment by Thanood** [comment] 2017-04-11 12:49
I still need to read through the issue, thanks for mentioning.

Typically, I would use this as a(nother) reason to throw inline views away and change the slider to a js/html duo. But I think this may also be an issue for the webpack team because Aurelia *does* support that. So I'm uncertain what to do now.

On the other hand, all I need is a repro and post it in the thread you've linked..

**Comment by eikaramba** [comment] 2017-04-11 13:04
Yes you are right. BTW: The workaround mentioned works. Not sure if that is good, but at least now i'm seeing my app again ;)

**Comment by eikaramba** [comment] 2017-04-12 12:03
So currently i have the mentioned dependency list above integrated and the workaround from https://github.com/aurelia/webpack-plugin/issues/101.

So far so good. Unfortunately i'm experiencing `.tooltip is not a function` and `.dropdown is not a function` errors. Materialize.js seems to be included in the webpack bundle. I already tried this hacky await workaround for AMB, where it waits until everything is initialized but no luck so far.

**Comment by Thanood** [comment] 2017-04-12 15:38
You found the classical "two jqueries" issue! 😃

**Comment by Thanood** [comment] 2017-04-12 19:15
@eikaramba If you have a webpack project ready, please try to pull from master, I've made the `PLATFORM.moduleName()` changes. 😃

**Comment by eikaramba** [comment] 2017-04-12 19:38
Just removed the ModuleDependencyPlugin, tried it and get:

`Unable to find module with ID: aurelia-materialize-bridge/autocomplete/autocomplete`

Unfurtunately even when adding everything back how it works now i get this again

`Failed loading required CSS file: aurelia-materialize-bridge/slider/slider.css`

Argh... actually i already fixed it by using that:

```
{
        test: /aurelia-materialize-bridge\/dist\/commonjs\/.*\.css$/,
        use: [
          {
            loader: 'raw-loader'
          }
        ]
      },

But even that does not work now, strange....
```

**Comment by Thanood** [comment] 2017-04-12 19:41
Sorry, I forgot the most important step.. Building the dist folder. It's running right now. 😃

**Comment by Thanood** [comment] 2017-04-12 19:43
Dist is built and uploaded. Sorry again.

**Comment by eikaramba** [comment] 2017-04-12 20:13
Good news: The CSS issue is gone and it works

Bad Bews: Still `Unable to find module with ID: aurelia-materialize-bridge/autocomplete/autocomplete`

**Comment by Thanood** [comment] 2017-04-12 20:21
Interesting.. Thanks for trying.
I'll look into that. Maybe I forgot something..

**Comment by Thanood** [comment] 2017-04-12 20:30
At first sight I'd say all attributes are missing while elements are in.

**Comment by Thanood** [comment] 2017-04-13 12:28
I'd like to save [this comment](https://github.com/aurelia/webpack-plugin/issues/107#issuecomment-293878340) for future reference...

**Comment by Thanood** [comment] 2017-04-17 08:18
@eikaramba 
Would you mind sharing your webpack config? I tried to apply `moduleName` correctly now (if you want to try, master is updated) but no css files are included, starting with `breadcrumbs` which seemed worked for you.

Here is mine (adapted from [webpack-plugin wiki](https://github.com/jods4/aurelia-webpack-build/wiki/Webpack-config)):

```js
const path = require("path");
const { AureliaPlugin } = require("aurelia-webpack-plugin");

module.exports = {
    entry: {
        "main": "aurelia-bootstrapper", // (1)
        "vendor": ["materialize-css", "jquery"]
    },

    output: {                                   // (2)
        path: path.resolve(__dirname, "dist"),
        publicPath: "dist",
        filename: "[name].js",
        chunkFilename: "[name].js",
    },

    resolve: {                                  // (3)
        extensions: [".ts", ".js"],
        modules: ["src", "node_modules"],
        alias: {
            '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
            'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
        }
    },

    module: {                                   // (4)
        rules: [
            { test: /\.less$/i, use: ["style-loader", "css-loader", "sass-loader"] },
            { test: /\.css$/i, use: ["style-loader", "css-loader"], issuer: /\.html?$/i },
            { test: /\.css$/i, use: ["style-loader", "css-loader"], issuer: /\.[tj]s$/i },
            { test: /\.ts$/i, use: "ts-loader" },
            { test: /\.html$/i, use: "html-loader" },
        ]
    },

    plugins: [
        new AureliaPlugin(),                       // (5)
    ],
};
```

Maybe I did something wrong.

**Comment by eikaramba** [comment] 2017-04-17 10:34
Sure no problem. It is based on the official skeleton webpack config.

```
const path = require("path");
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const { AureliaPlugin, ModuleDependenciesPlugin } = require("aurelia-webpack-plugin");
const { optimize: { CommonsChunkPlugin }, ProvidePlugin } = require('webpack')
const { attributes } = require("aurelia-webpack-plugin/dist/html-requires-loader");

// config helpers:
const ensureArray = (config) => config && (Array.isArray(config) ? config : [config]) || []
const when = (condition, config, negativeConfig) =>
  condition ? ensureArray(config) : ensureArray(negativeConfig)

// primary config:
const outDir = path.resolve(__dirname, 'dist');
const srcDir = path.resolve(__dirname, 'src');
const nodeModulesDir = path.resolve(__dirname, 'node_modules');
const baseUrl = '/';

attributes["router-view"] = [ "layout-view" ];

const cssRules = (production)=>{return [
  { loader: 'css-loader',
    options: {
              minimize: production
            }
 },
  {
    loader: 'postcss-loader',
    options: { plugins: () => [require('autoprefixer')({ browsers: ['last 2 versions'] })]}
  },
  'sass-loader'
]}

module.exports = ({production, server, extractCss, coverage} = {}) => ({
  resolve: {
    extensions: ['.js'],
    modules: [srcDir, 'node_modules'],
    alias: {
      '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
      'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
    }
  },
  entry: {
    app: ['aurelia-bootstrapper'],
    vendor: ['bluebird', 'jquery'],
  },
  output: {
    path: outDir,
    publicPath: baseUrl,
    filename: production ? '[name].[chunkhash].bundle.js' : '[name].[hash].bundle.js',
    sourceMapFilename: production ? '[name].[chunkhash].bundle.map' : '[name].[hash].bundle.map',
    chunkFilename: production ? '[chunkhash].chunk.js' : '[hash].chunk.js',
  },
  devServer: {
    contentBase: baseUrl,
    historyApiFallback: {
      index: '/'
    }
  },
  module: {
    rules: [
      // CSS required in JS/TS files should use the style-loader that auto-injects it into the website
      // only when the issuer is a .js/.ts file, so the loaders are not applied inside html templates
      {
        test: /(master\.scss|\.css)$/i, // My main css file is master.scss, would i process ALL scss files it would have problems as there are a lot that are depending on each other and do not compile on their own
        issuer: [{ not: [{ test: /\.html$/i }] }],
        use: extractCss ? ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: cssRules(production),
        }) : ['style-loader', ...cssRules(production)],
      },
      {
        test: /\.png$/i,
        use: [
          {
            loader: "file-loader?name=[path][name].[ext]&context=./src/assets/images"
          }
        ]
      },
      {
        test: /\.css$/i,
        issuer: [{ test: /\.html$/i }],
        // CSS required in templates cannot be extracted safely
        // because Aurelia would try to require it again in runtime
        use: cssRules(production),
      },
      { test: /\.html$/i, loader: 'html-loader' },
      { test: /\.js$/i, loader: 'babel-loader', exclude: nodeModulesDir },
      { test: /\.json$/i, loader: 'json-loader' },
      // use Bluebird as the global Promise implementation:
      { test: /[\/\\]node_modules[\/\\]bluebird[\/\\].+\.js$/, loader: 'expose-loader?Promise' },
      // exposes jQuery globally as $ and as jQuery:
      { test: require.resolve('jquery'), loader: 'expose-loader?$!expose-loader?jQuery' },
      // embed small images and fonts as Data Urls and larger ones as files:
      { test: /\.(png|gif|jpg|cur)$/i, loader: 'url-loader', options: { limit: 8192 } },
      { test: /\.woff2(\?v=[0-9]\.[0-9]\.[0-9])?$/i, loader: 'url-loader', options: { limit: 10000, mimetype: 'application/font-woff2' } },
      { test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9])?$/i, loader: 'url-loader', options: { limit: 10000, mimetype: 'application/font-woff' } },
      // load these fonts normally, as files:
      { test: /\.(ttf|eot|svg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/i, loader: 'file-loader' },
      ...when(coverage, {
        test: /\.[jt]s$/i, loader: 'istanbul-instrumenter-loader',
        include: srcDir, exclude: [/\.{spec,test}\.[jt]s$/i],
        enforce: 'post', options: { esModules: true },
      }),
    ]
  },
  plugins: [
    new AureliaPlugin(),
    new ModuleDependenciesPlugin({
      "aurelia-materialize-bridge": [
'./autocomplete/autocomplete',
'./badge/badge',
'./box/box',
'./breadcrumbs/breadcrumbs',
'./breadcrumbs/instructionFilter',
'./button/button',
'./card/card',
'./carousel/carousel-item',
'./carousel/carousel',
'./char-counter/char-counter',
'./checkbox/checkbox',
'./chip/chip',
'./chip/chips',
'./collapsible/collapsible',
'./collection/collection-header',
'./collection/collection-item',
'./collection/collection',
'./collection/md-collection-selector',
'./colors/colorValueConverters',
'./colors/md-colors',
'./common/attributeManager',
'./common/attributes',
'./common/constants',
'./common/events',
'./datepicker/datepicker-default-parser',
'./datepicker/datepicker',
'./dropdown/dropdown-element',
'./dropdown/dropdown',
'./dropdown/dropdown-fix',
'./fab/fab',
'./file/file',
'./footer/footer',
'./input/input-prefix',
'./input/input-update-service',
'./input/input',
'./modal/modal',
'./modal/modal-trigger',
'./navbar/navbar',
'./pagination/pagination',
'./parallax/parallax',
'./progress/progress',
'./pushpin/pushpin',
'./radio/radio',
'./range/range',
'./scrollfire/scrollfire-patch',
'./scrollfire/scrollfire-target',
'./scrollfire/scrollfire',
'./scrollspy/scrollspy',
'./select/select',
'./sidenav/sidenav-collapse',
'./sidenav/sidenav',
'./slider/slider',
'./switch/switch',
'./tabs/tabs',
'./toast/toastService',
'./tooltip/tooltip',
'./transitions/fadein-image',
'./transitions/staggered-list',
'./validation/validationRenderer',
'./waves/waves',
'./well/md-well.html' //The only one that i needed to add manually by hand, the rest was copy&pasted
      ],
    }),
    new ProvidePlugin({
      'Promise': 'bluebird',
      '$': 'jquery',
      'jQuery': 'jquery',
      'window.jQuery': 'jquery',
    }),
    new HtmlWebpackPlugin({
      template: 'index.ejs',
      minify: production ? {
        removeComments: true,
        collapseWhitespace: true
      } : undefined,
      metadata: {
        // available in index.ejs //
        server, baseUrl
      },
    }),
    ...when(extractCss, new ExtractTextPlugin({
      filename: production ? '[contenthash].css' : '[id].css',
      allChunks: true,
    })),
    ...when(production, new CommonsChunkPlugin({
      name: ['common']
    })),
    ...when(production, new CopyWebpackPlugin([
      { from: 'favicon.ico', to: 'favicon.ico' }
    ]))
  ],
})
```

**Comment by Thanood** [comment] 2017-04-19 05:21
I don't get it somehow..

The first component with css (breadcrumbs) throws an error `Error: Failed loading required CSS file: aurelia-materialize-bridge/breadcrumbs/breadcrumbs.css` - but the file is bundled and already loaded as a script tag.

I can't see what's wrong right now.
Will upload a repo in a few minutes (when my computer stops hanging).

**Comment by eikaramba** [comment] 2017-04-19 12:56
Just cloned the repo and can reproduce it. Tried to fix it without any luck, however it actually disappears when using latest "0.27.0" version. So this particular error is happening because of the changes. i will look further if i find anything

**Comment by eikaramba** [comment] 2017-04-19 13:03
okay a little bit further:

remove this line https://github.com/Thanood/md-todo-webpack/blob/master/webpack.config.js#L22, it causes problems as CSS required in templates cannot be extracted safely because Aurelia would try to require it again in runtime.

**Comment by eikaramba** [comment] 2017-04-19 13:27
i created a pull request, still not working 100%, but now it seems to be about how the elements are injected.

`Error: No Aurelia APIs are defined for the element: "ADD-TODO-MODAL".`

**Comment by Thanood** [comment] 2017-04-19 13:47
wtf... Thanks! 👍 
😂 

Okay, the last one is probably because of `features`. I've seen something in the wiki.

**Comment by Thanood** [comment] 2017-04-19 13:48
> remove this line https://github.com/Thanood/md-todo-webpack/blob/master/webpack.config.js#L22,

Can you explain how that works? because I've had a version without that and I had the same errors..

**Comment by Thanood** [comment] 2017-04-19 19:52
That works now in [md-todo-webpack](). Great help there with this PR: https://github.com/Thanood/md-todo-webpack/pull/1 👍 

The documentation needs an update now as @eikaramba suggested. So please don't close this issue as a reminder for me.

**Comment by Thanood** [comment] 2017-04-24 18:32
Lack of time atm.. I want to release this change along with the documentation.
I hope I can do a release this week.

**Comment by HIRANO-Satoshi** [comment] 2017-05-21 04:00
I'm following the instruction for webpack 2.

https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation/webpack-2.x.html

I experienced ".dropdown is not a function errors" and found webpack.config.js should have the following *alias: {..}* as described above.

```
module.exports = ({production, server, extractCss, coverage} = {}) => ({
  resolve: {
    extensions: ['.ts', '.js'],
      modules: [srcDir, 'node_modules'],
      alias: {
          '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
          'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
      }
  },
```

Also, a line in main.ts:

```
    aurelia.start().then(a => a.setRoot());
```

in the instruction should be;

```
    aurelia.start().then(() => aurelia.setRoot(PLATFORM.moduleName('app')));
```

main.ts should also have the following code as described in #337 .


```
function waitForMaterialize() {
  return new Promise((resolve, reject) => {
    let iterations = 0;
    const handler = window.setInterval(() => {
      iterations++;
      let ma = (window as any).Materialize;
      if (
        ma.elementOrParentIsFixed &&
        ma.escapeHash &&
        ma.fadeInImage &&
        ma.guid &&
        ma.scrollFire &&
        ma.showStaggeredList &&
        ma.toast &&
        ma.updateTextFields
      ) {
        console.log(`waited ${iterations} iterations for Materialize to finish loading`);
        window.clearInterval(handler);
        resolve();
      }
    }, 1);
  });
}

export async function configure(aurelia: Aurelia) {
    // https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/337
    // without this we have "Uncaught TypeError: Materialize.updateTextFields is not a function".
    // Remove this when the issue is closed.
    await waitForMaterialize();
    
    aurelia.use
        .standardConfiguration()
        .developmentLogging()
...
```

PLATFORM.moduleName() is needed at many places.

Now my app seems running except it couldn't load images from the img folder.

**Comment by Thanood** [comment] 2017-05-21 20:23
Wow, thanks a lot! 👍

**Comment by HIRANO-Satoshi** [comment] 2017-05-26 01:42
> Now my app seems running except it couldn't load images from the img folder.

Images appeared with the default webpack.config.js except a splash image used in the top index.ejs.

The splash image is used *before* /static/styles.css and the image loader start working.

While images do not work, icons work. So, you can use an icon such as restore_page icon as this index.ejs.

```
<html>
  <head>
    <meta charset="utf-8">
    <title><%- htmlWebpackPlugin.options.metadata.title %></title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <base href="<%- htmlWebpackPlugin.options.metadata.baseUrl %>">
    <!-- imported CSS are concatenated and added automatically -->
  <style>
    .splash {
      text-align: center;
      margin: 10% 0 0 0;
      box-sizing: border-box;
    }

    .splash .message {
      font-size: 20px;
      /* add as you like */
    }

    .splash .loading {
      text-align: center;
      display: inline-block;
      margin-top: 40px;
      font-size: 42px;
      color: #ee6e73;
    }
  </style>
  
  <body aurelia-app="main">
      <div class="splash">
        <div class="message">Loading <%- htmlWebpackPlugin.options.metadata.title %></div>
        <i class="loading material-icons">restore_page</i>
      </div>
      <% if (htmlWebpackPlugin.options.metadata.server) { %>
      <!-- Webpack Dev Server reload -->
      <script src="/webpack-dev-server.js"></script>
      <% } %>
  </body>
</html>
```

**Comment by R74NN** [comment] 2018-01-16 09:32
I've tried all workarounds posted here, including ModuleDependenciesPlugin and the issue is still present. Currently I'm using bridge 0.31, materialize-css 0.100.2 and webpack 3.10. I've tried other version combinations metioned here with no luck.

**Comment by MaximBalaganskiy** [comment] 2018-01-16 10:18
@R74NN here is `webpack.config.js` which works in your project

```
const fs = require('fs');
const path = require("path");
const webpack = require("webpack");
const { AureliaPlugin, ModuleDependenciesPlugin, GlobDependenciesPlugin } = require("aurelia-webpack-plugin");
const bundleOutputDir = "./wwwroot/dist";
const nodeModules = path.join(process.cwd(), 'node_modules');
const realNodeModules = fs.realpathSync(nodeModules);

module.exports = (env) => {
	const isDevBuild = !(env && env.prod);
	return [{
		entry: { "app": ["aurelia-bootstrapper"] },
		resolve: {
			extensions: [".ts", ".js"],
			modules: ["ClientApp", "node_modules"]
		},
		output: {
			path: path.resolve(bundleOutputDir),
			publicPath: "dist/",
			filename: "[name].js",
			chunkFilename: "[name].js"
		},
		module: {
			rules: [
				{ test: /\.(png|woff|woff2|eot|ttf|svg)(\?|$)/, loader: "url-loader?limit=100000" },
				{ test: /\.ts$/i, include: [/ClientApp/, /node_modules/], use: "ts-loader?silent=false" },
				{ test: /\.html$/i, use: "html-loader" },
				{ test: /\.css$/i, use: isDevBuild ? "css-loader" : "css-loader?minimize" },
				{
					test: /\.scss$/i,
					use: [
						{ loader: isDevBuild ? "css-loader" : "css-loader?minimize" },
						{ loader: "sass-loader" }
					]
				}
			]
		},
		plugins: [
			new webpack.DefinePlugin({ IS_DEV_BUILD: JSON.stringify(isDevBuild) }),
			new webpack.ProvidePlugin({ $: "jquery", jQuery: "jquery", "window.jQuery": "jquery" }),
			new AureliaPlugin({ aureliaApp: "configure", includeAll: "ClientApp" }),
			new ModuleDependenciesPlugin({
				"aurelia-authentication": ["./authFilterValueConverter"],
				//"aurelia-chart": ["./elements/chart-element", "./attributes/chart-attribute"]
			}),
			new webpack.optimize.CommonsChunkPlugin({
				"name": ["vendor"],
				"minChunks": (module) => {
					return module.resource && (module.resource.startsWith(nodeModules) || module.resource.startsWith(realNodeModules));
				},
				"chunks": ["app"]
			})
		].concat(isDevBuild ? [
			new webpack.SourceMapDevToolPlugin({
				filename: "[file].map", // Remove this line if you prefer inline source maps
				moduleFilenameTemplate: path.relative(bundleOutputDir, "[resourcePath]")  // Point sourcemap entries to the original file locations on disk
			})
		] : [
				new webpack.optimize.UglifyJsPlugin()
			])
	}];
};

```

**Comment by R74NN** [comment] 2018-01-16 10:53
Thanks, but what exactly is wrong with my config? I'd like to know and modify it accordingly.

**Comment by MaximBalaganskiy** [comment] 2018-01-16 11:01
A couple of things:

* most importantly, you need to add `new AureliaPlugin({ aureliaApp: undefined, dist: "native-modules" })` to your vendor bundle. For details, see https://github.com/aspnet/templating/pull/37

* secondly, in loaders replace `{ test: /\.css(\?|$)/, loader: extractCSS.extract([isDevBuild ? "css-loader" : "css-loader?minimize"]) }` with `{ test: /\.css(\?|$)/, loader: isDevBuild ? "css-loader" : "css-loader?minimize" }`

**Comment by R74NN** [comment] 2018-01-16 11:35
Thanks again! And sorry for bothering you further. Is there a way to make it work with ExtractTextWebpackPlugin, so I can load .css files separately?

**Comment by MaximBalaganskiy** [comment] 2018-01-16 12:23
Have a look a this post https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/401#issuecomment-294447485

You cannot extract css required from html. That is why the author uses separate rule for those cases and respective CSS is always going to be in JS bundle

**Closed** 2018-04-17 23:36 UTC
Labels: enhancement, needs documentation
