### ISSUE TITLE
Aurelia CLI installation not working when materialize dependencies are in a separate bundle

### ISSUE THREAD

**Issue by lebolo** [aurelia-ui-toolkits/aurelia-materialize-bridge#296] opened 2016-10-19 19:37 UTC
Windows 7 64-bit
au -v: 0.21.0
node -v: v6.8.0
npm -v: 3.10.8

---------------------------

I am trying to follow the [instructions](https://aurelia-ui-toolkits.gitbooks.io/materialize-bridge-docs/content/installation.html) for installing via Aurelia CLI.

**I have added a custom task after build that moves all bundle and HTML files to a dist folder.**

If I do what the page recommends and add a separate `materialize-bundle.js` in `aurelia.json`:

```javascript
{
  "name": "materialize-bundle.js",
  "dependencies": [
    "jquery",
    {
      "name": "materialize-css",
      "path": "../node_modules/materialize-css/dist",
      "main": "js/materialize.amd",
      "deps": [
        "jquery"
      ],
      "resources": [
        "css/materialize.css"
      ],
      "exports": "Materialize"
    },
    {
      "name": "aurelia-materialize-bridge",
      "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
      "main": "index",
      "deps": [
        "jquery"
      ],
      "resources": [
        "**/*.{css,html}"
      ]
    }
  ]
}
```

Then I get an error that `.../node_modules/aurelia-materialize-bridge/dist/amd/index.js` is not found when I try to load my page.

![image](https://cloud.githubusercontent.com/assets/2286572/19534284/2ba936c4-9611-11e6-9f89-c0fb91403c1d.png)

I haven't tried adding this file/directory structure to `dist`, as it seemed odd that Aurelia would expect a `node_modules` directory for anything post-build.

If I instead add the materialize bundle as dependencies to my `vendor-bundle.js`:

```javascript
{
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "scripts/require.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-templating-binding",
          {
            "name": "text",
            "path": "../scripts/text"
          },
          {
            "name": "aurelia-templating-resources",
            "path": "../node_modules/aurelia-templating-resources/dist/amd",
            "main": "aurelia-templating-resources"
          },
          {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev"
          },
          {
            "name": "aurelia-validation",
            "path": "../node_modules/aurelia-validation/dist/amd",
            "main": "aurelia-validation"
          },
          ///// Materialize config -- this comment doesn't exist in the json file
          "jquery",
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "deps": [
              "jquery"
            ],
            "resources": [
              "css/materialize.css"
            ],
            "exports": "Materialize"
          },
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "**/*.{css,html}"
            ]
          }
        ]
      }
```

Then `index.js` is never requested (as I assume it shouldn't be if everything was bundled correctly).

![image](https://cloud.githubusercontent.com/assets/2286572/19534369/79995ac6-9611-11e6-9fc4-c3535bbafda5.png)

Why does it not work when I try to follow the instructions and separate out materialize dependencies as a separate bundle?

**Comment by Thanood** [comment] 2016-10-19 19:55
Can you please check if `node_modules/aurelia-materialize-bridge/dist/amd/index.js` is actually there?

The `index.js` should always be loaded so I guess it's there because when you add Materalize to `vendor-bundle` everything works (right?).. But just to make sure, please check. 😃 

> I have added a custom task after build that moves all bundle and HTML files to a dist folder.

Can you check if it works when you don't do this?

Also, please check both your local *and* global version of `aurelia-cli`. Both should be at `0.21.0`.

**Comment by lebolo** [comment] 2016-10-19 20:03
> Can you please check if `node_modules/aurelia-materialize-bridge/dist/amd/index.js` is actually there?

It exists :)

> Can you check if it works when you don't do this?

It "works" but only because it's requesting **and now finding** `node_modules/aurelia-materialize-bridge/dist/amd/index.js`.

![image](https://cloud.githubusercontent.com/assets/2286572/19535325/2321aadc-9615-11e6-8b1b-a0277b309bf8.png)

I confirmed that it's the actual file under `node_modules` by modifying it and refreshing the page without re-building. I see my modification in the debugger.

**Comment by Thanood** [comment] 2016-10-19 20:07
> I confirmed that it's the actual file under node_modules by modifying it and refreshing the page without re-building.

That means it doesn't use the bundle, right? Strange.
We've had several "interesting" issues with older local aurelia-cli versions. Can you please post your version (`au -v`).

I do this like twice a day atm so this seems really strange to me. :)

**Comment by lebolo** [comment] 2016-10-19 20:18
`au -v` is `0.21.0` (I thought this was global). If I do `npm ls --depth=0` I see `aurelia-cli@0.21.0` (which I thought was local).

**Comment by Thanood** [comment] 2016-10-19 20:27
Hmm...
Can you please check if [this repo](https://github.com/aurelia-ui-toolkits/cm-bridges/tree/master/materialize) runs?

If so, would you mind to upload your project or a reproduction? I'm really curious what's going on..

**Comment by lebolo** [comment] 2016-10-19 20:47
So I cloned the repo, ran `npm install` and then `au run`.

It "works" (only because it's looking for and finding `node_modules/aurelia-materialize-bridge/dist/amd/index.js` :wink:), so it still has bundle issues.

![image](https://cloud.githubusercontent.com/assets/2286572/19536575/845c08b0-961a-11e6-92f6-4728f359f4f8.png)

I noticed `au -v` gave me `0.20.2`. I updated to `0.21.0` and ran with the same results.

I'll try to upload my project as a repo.

**Comment by Thanood** [comment] 2016-10-19 20:55
Thanks, I see it now. No need to upload anything, I guess.
The bundle is loaded after `index.js` - atm I'm suspecting the plugin load line in `main.js`..

**Comment by Thanood** [comment] 2016-10-19 21:12
Okay so, if you move the bridge configuration out of the separate bundle into `vendor-bundle` it works (without loading `index.js`).

I guess this is because of `aurelia.use.plugin('aurelia-materialize-bridge', b => b.useAll());` in `main.js`. This loads `index.js` and configured the plugin. This should be loaded from the bundle, not from node_modules.

So I added `index.js` to the resources array, like this:

```json
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "**/*.{css,html}",
              "index.js"
            ]
          }
```

And no `index.js` loaded. 😃 
I'll add this to the docs. Maybe you'd like to confirm.

**Comment by Thanood** [comment] 2016-10-19 21:14
**But** I guess I'll check back in aurelia-cli itself if this is intended. I mean `index.js` *is*  the main entry point. This should be obvious to add to the bundle.

**Comment by Thanood** [comment] 2016-10-19 21:24
I've added `aurelia-v-grid` to the app. This is also a plugin which uses a config builder.
The effect is the same, `index.js` is requested from `node_modules` instead of the bundle. Adding `index.js` to the resources array fixes this.

@lebolo I big **thanks** for this issue report! 😃

**Comment by Thanood** [comment] 2016-10-19 21:40
https://github.com/aurelia/cli/issues/384

**Comment by lebolo** [comment] 2016-10-19 23:28
Confirmed that your fix works perfectly! Thanks @Thanood!

I'll let you close this issue in case you need it open for anything.

**Comment by Thanood** [comment] 2016-10-20 08:07
Thanks for not closing the issue. :smiley: 
I've made the changes to the documentation now.

**Closed by Thanood** 2016-10-20 08:07 UTC
Labels: needs documentation
