### ISSUE TITLE
Add installation instructions for Aurelia-CLI

### ISSUE THREAD

**Issue by AnderssonPeter** [aurelia-ui-toolkits/aurelia-materialize-bridge#205] opened 2016-07-08 11:17 UTC
Please add installation instructions for Aurelia-CLI, and while you are at it please do the same for typescript!

**Comment by Thanood** [comment] 2016-07-11 11:10
@AnderssonPeter 

According to [this comment]((https://github.com/aurelia/cli/issues/212#issuecomment-230163450) plugins with html templates don't seem to be supported in aurelia-cli, yet. We're making heavy use of html templates so I guess this won't work.

Or did you by chance get this to work?

**Comment by AnderssonPeter** [comment] 2016-07-11 14:42
@Thanood Thanks for the response, i haven't tried yet i have i just wanted some pointers on how to do it but i guess atm its not possible.

**Comment by Thanood** [comment] 2016-07-13 18:23
Keeping this open to track `aurelia-cli` integration progress.

**Comment by Thanood** [comment] 2016-07-21 18:32
https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/570

**Comment by AnderssonPeter** [comment] 2016-07-28 09:18
Issue for Aurelia-CLI: https://github.com/aurelia/cli/issues/202

**Comment by tdamir** [comment] 2016-07-29 20:43
There are couple of issues to solve. 

1. First there is an issue with bridge not exporting all components so the Aurelia CLI bundler will not be able to bundle js files. I've made a fork which exports all types. (This is optional. You can install the original module instead, but the components will not be bundled.)
npm install github:tdamir/aurelia-materialize-bridge --save
or if it's not an issue to have a lot of requests on page load:
npm install github:aurelia-ui-toolkits/aurelia-materialize-bridge --save

2. Unfortunately the materialize-css will not work well with Aurelia CLI bundler. You have to replace the original with the fixed one:
npm install github:ccloi/materialize#AMD-fix --save

3. Then you have to register the installed modules in aurelia.json as vendor-bundle dependencies:
```javascript
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "resources": [
              "./**/*.{css,html}"
            ]
          },
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.min",
            "deps": [
              "jquery"
            ],
            "resources": [
              "css/materialize.css"
            ]
          },
```

4. In you main.ts insert:
```javascript
import 'materialize-css';
```

**Comment by Thanood** [comment] 2016-07-29 23:20
@tdamir Very interesting, thanks!

I hope that point 1 can be solved with another approach (the kendoui team is preparing a documentation about that approach). But it's an interesting variation that might also solve the `resource` spam for webpack.

Using a fork is a little unfortunate (unless it is updated properly) but having seen all the problems with materialize and requirejs in their issues, I understand that it's necessary.

Depending on how point 1 turns out, I'll update the documentation after I've tested this.

**Comment by tdamir** [comment] 2016-08-01 19:29
@Thanood Sorry. This is a correct URL: https://github.com/ccloli/materialize. I'll update the original comment too.

**Comment by Thanood** [comment] 2016-08-10 08:12
Did you also get these `Unexpected token: {` or `Unexpected token: <` errors while the bundle included html templates or css fragments not wrapped in a `define`? I wonder if that's a CLI bug..

**Comment by Thanood** [comment] 2016-08-10 08:47
It worked when I changed dependency configuration to this:

```json
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "resources": [
              "./**/*.{html}",
              "./**/*.{css}"
            ]
          }
```

**Comment by Thanood** [comment] 2016-08-10 08:53
That works! :smile: :sparkles:

**Comment by tdamir** [comment] 2016-08-10 09:04
Great! Thanks for exporting all the classes. It should work with stub:true option too.

**Comment by Thanood** [comment] 2016-08-10 09:14
Well, it didn't work for me and I'm still getting `Unexpected token: <` in another project (similar structure). I'm really wondering why that happens but I find it complicated for now (at work and need to do some other things. :wink: ) to create a repro and open an issue with aurelia-cli.

**Comment by tdamir** [comment] 2016-08-10 09:25
Sometimes I'm also getting those errors. Usually rebuild helps. If the app is running (i.e.: au run --watch), then cancel it before rebuilding. I'll try to reproduce the issue on clean project when I find some time.

**Comment by tdamir** [comment] 2016-08-10 11:55
I just tried to integrate the bridge in a project created with latest aurelia-cli (0.17.0) without luck. I'm always getting those error(s) regardless of stub value. I agree that it could be an issue with aurelia-cli tracer (it randomly stops: sometimes collection.html, sometimes some other file...). I compared the configs with my working project and couldn't find any difference... Strange... I'll investigate it when I have more time.

**Comment by Thanood** [comment] 2016-08-10 13:56
I've raised a question here: :point_up: [10. August 2016 11:18](https://gitter.im/aurelia/Discuss?at=57aaf174f7f11a7936b1c807)

No answer yet but it's there (and now it's linked so I won't forget :wink: ).

**Comment by andreaszeuch** [comment] 2016-08-28 23:23
Any update on this problem? Sometimes it runs perfectly fine, sometimes it just stops working entirely and I'm forced to create a new aurelia project. Would love a fix

**Comment by Thanood** [comment] 2016-08-29 09:02
No "real" news here, except this sounds to be related: https://github.com/aurelia/cli/issues/294

**Comment by Ullfis** [comment] 2016-08-29 15:27
aurelia-cli 0.18 

The *not adding define('text!…* problem and Unexpected token goes away by adding all css/html in resources.

```json

          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "breadcrumbs/breadcrumbs.css",
              "breadcrumbs/breadcrumbs.html",
              "card/card.css",
              "card/card.html",
              "carousel/carousel-item.html",
              "carousel/carousel.css",
              "carousel/carousel.html",
              "checkbox/checkbox.html",
              "chip/chip.html",
              "collection/collection-header.css",
              "collection/collection-header.html",
              "collection/collection-item.css",
              "collection/collection-item.html",
              "collection/collection.html",
              "collection/md-collection-selector.css",
              "collection/md-collection-selector.html",
              "colors/md-colors.html",
              "dropdown/dropdown-element.html",
              "fab/fab.html",
              "file/file.html",
              "input/input.css",
              "input/input.html",
              "navbar/navbar.css",
              "navbar/navbar.html",
              "pagination/pagination.html",
              "progress/progress.html",
              "radio/radio.html",
              "range/range.html",
              "sidenav/sidenav.css",
              "sidenav/sidenav.html",
              "slider/slider.css",
              "switch/switch.css",
              "switch/switch.html",
              "well/md-well.html"
            ]
          }

```

**Comment by Thanood** [comment] 2016-08-29 15:43
Great find! :+1:

**Comment by Thanood** [comment] 2016-08-29 19:10
I wonder if we can simply add these to build resources in `package.json`..

**Comment by Ullfis** [comment] 2016-08-29 19:23
Fantastic! it worked :smile:

Missing navbar in my tiny test project..

**Comment by Ullfis** [comment] 2016-08-29 20:40
[Here](https://github.com/Ullfis/aurelia-cli-materialize-bridge) is what i have now

**Comment by Thanood** [comment] 2016-08-29 20:53
> npm install requirejs materialize-css --save-dev

No fork? That would be awesome!

**Comment by Ullfis** [comment] 2016-08-30 07:55
btw.. [here](https://github.com/Ullfis/aurelia-materialize-bridge/blob/build-resources/list-resources.js) is some code to list resources in your project

**Comment by andreaszeuch** [comment] 2016-08-31 12:20
@Ullfis First of: thanks for your work, still not working tho, getting a new error in browser console now

Uncaught TypeError: Cannot read property '__useDefault' of undefined

Everything else works fine, the building process and all.

I'm not using the typescript project, could this be a problem?

**Comment by Ullfis** [comment] 2016-08-31 13:23
I just tried with a new esnext project and it work on my computer.

My stuff:

```
$ au -v
0.18.0
$ node -v
v6.5.0
$ npm -v
3.10.3
```

aurelia-materialize-bridge@0.14.0

[aurelia.json](https://github.com/Ullfis/aurelia-cli-materialize-bridge/blob/master/aurelia_project/aurelia.json)

Firefox
Crome

Disable cache (while DevTools is open)

Linux Mint

---


Could you try a new typescript project in a temporary folder?

**Comment by andreaszeuch** [comment] 2016-08-31 13:40
@Ullfis For whatever reason it works now, just started a new project (again), confirmed working for typescript and esnext, thanks!

**Comment by Thanood** [comment] 2016-09-07 19:03
Added aurelia-cli installation instructions:
http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation

**Comment by Ganbin** [comment] 2016-09-08 13:44
I don't understand the comment :

> Add rbuild.js and materialize-css.js

What that mean?

**Comment by Thanood** [comment] 2016-09-08 13:46
Thanks for your comment @Ganbin and I think you're perfectly right.
This means "add the linked files rbuild.js and materialize-css.js to your project root directory"..

I will add this to the instructions, therefore I reopen this issue.

**Comment by Ganbin** [comment] 2016-09-08 13:48
Ok thanks I was suspecting it was that because of the next command line but it could be more clear. Thanks for precision.

**Comment by Ganbin** [comment] 2016-09-08 14:10
I have follow your instruction but when I run au build` I get this error :

```
{ uid: 0,
  name: '<series>',
  branch: true,
  error: 
   { [Error: ENOENT: no such file or directory, open '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/src/waves.js']
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/src/waves.js',
     moduleTree: [ 'materialize-css/js/materialize.amd' ],
     fileName: '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/node_modules/materialize-css/dist/js/materialize.amd.js' },
  duration: [ 2, 494327414 ],
  time: 1473343669846 }
{ [Error: ENOENT: no such file or directory, open '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/src/waves.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/src/waves.js',
  moduleTree: [ 'materialize-css/js/materialize.amd' ],
  fileName: '/Users/User/Sites/Wakanda/workHours/workHours/web/aurelia/node_modules/materialize-css/dist/js/materialize.amd.js' }
```

My CLI is in version `0.18.0`

**Comment by Thanood** [comment] 2016-09-08 14:28
Strange.. I did this twice today and it did work..
Did `./node_modules/.bin/r.js -o rbuild.js` go smooth or were there any errors?

**Comment by Ganbin** [comment] 2016-09-08 14:38
it was going smooth. I will investigate tomorrow on it.

**Comment by Ganbin** [comment] 2016-09-08 14:49
Nevermind I fix it.

I have remove the materialize-css and requirejs dependencies and do again this two line : 

`npm install requirejs materialize-css --save-dev`
`./node_modules/.bin/r.js -o rbuild.js`

And it make it work...

**Comment by Thanood** [comment] 2016-09-08 15:10
Interesting..
Any idea why the first set of these dependencies did not work? Wrong versions perhaps?

**Comment by Thanood** [comment] 2016-09-09 05:25
fixed the description
http://aurelia-ui-toolkits.github.io/demo-materialize/#/installation 😃

**Closed by Thanood** 2016-09-09 05:25 UTC
Labels: needs documentation

**Comment by dpinart** [comment] 2016-09-20 23:07
Hi

I'm on windows 10 and followed installation instructions but I can't complete step '$ ./node_modules/.bin/r.js -o rbuild.js'

I run node ./node_module/,bin/r.js -o rbuild.js and got followinf error:
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3


I have rbuild.js and materialize-css.js at project root folder, at same level of index.html

**Comment by tdamir** [comment] 2016-09-21 07:30
Hi,

On windows, instead of run.js you have to execute run.js.cmd so you command should look like this: ./node_modules/.bin/r.js.cmd -o rbuild.js

**Comment by Thanood** [comment] 2016-09-21 07:47
I will have to clarify this in the instructions.

@tdamir is right, either use `r.js.cmd` or use a bash-compatible shell (f.i. gitbash, which comes with git for Windows). The latter is also recommended by Aurelia team and I personally recommend it, too because it helps with some problems with npm. :smiley:

**Comment by J4ck4l0pe** [comment] 2016-10-14 12:19
`$ ./node_modules/.bin/r.js.cmd -o rbuild.js`
`bash: ./node_modules/.bin/r.js.cmd: No such file or directory`

Is this another npm package I should install first?

**Comment by lebolo** [comment] 2016-10-19 19:40
I getting an error when I follow these instructions, I opened a new issue under #296.
