### ISSUE TITLE
webpack implementation

### ISSUE THREAD

**Issue by hwaastad** [aurelia-ui-toolkits/aurelia-materialize-bridge#144] opened 2016-03-19 18:36 UTC
Hi,
I tested out the aurelia-es2016-webpack skeleton and have som issues with the bridge.

Do you have any recommendation on how to use this library together with webpack?

/hw

**Comment by adriatic** [comment] 2016-03-19 18:51
Without knowing what precisely is your issue @hwaastad - I would think that you encountered the problem described as "Extending the es2016-webpack sample to use Aurelia-KendoUI bridge fails" and discussed here: https://github.com/aurelia/skeleton-navigation/issues/344

There should not be any difference between KendoUI and Materialize bridge in this context.

**Comment by hwaastad** [comment] 2016-03-19 20:47
Hi @adriatic ,
much the same. After some trouble with missing libs (needed manual install) I ended up with:
webpack.config:
 resolve: {
        alias: {
            'aurelia-materialize-bridge': 'aurelia-materialize-bridge/dist/commonjs/index.js',
            'jQuery':'jquery/dist/jquery.js'
        }
    },

and in my main.js:
import 'aurelia-materialize-bridge';

Now, I see config-builder and toastService is loaded, but initialization fails:
Uncaught (in promise) Error: Cannot find module './aurelia-materialize-bridge'.(…)

I thing maybe I need to have a check with the aurelia-webpack-loader for more info.

thx

/hw

**Comment by adriatic** [comment] 2016-03-19 21:09
While your approach may result with the outcome you need - it is not the optimal one. I would suggest to wait until the developer maintaining Aurelia webpack project resolves the problem(s) reported in https://github.com/aurelia/skeleton-navigation/issues/344. At that time, your Materialize bridge based application would behave no different than the current es2016-webpack navigation skeleton.

The problems introduced by adding the bridge to the mix are caused by webpack failing to load all of the bridge's dependencies

**Comment by Thanood** [comment] 2016-03-20 17:59
> Uncaught (in promise) Error: Cannot find module './aurelia-materialize-bridge'.(…)

I got that part solved at work, would have to look it up there. But then there are problems finding hammerjs, Velocity etc. There are issues on the Materialize repo about webpack problems with workarounds.

I suppose webpack integration will be a broader topic than it seems.

**Comment by Thanood** [comment] 2016-03-21 22:34
adding
```
"main": "dist/commonjs/index.js"
```

to the bridge's package.json file should at least enable it to load. Somehow I missed adding this to 0.2.0. Sorry, will deliver a patch tomorrow or the day after.

Unfortunately, that is the time when Materialize's own problems with webpack start becoming an issue. I didn't have enough time yet to have a deeper look at these.

For reference..
These are Materializes issues on webpack, some of them include workarounds:
https://github.com/Dogfalo/materialize/issues?utf8=%E2%9C%93&q=is%3Aissue+webpack

This is maybe the most "significant" or at least it describes the problems I have had with it:
https://github.com/Dogfalo/materialize/issues/1422

**Comment by adriatic** [comment] 2016-03-21 23:31
everyone interested in webpack regardless of which bridge used - please participate in https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/428 and try to use @JeroenVinke as the proxy. This is important to simplify the discussion with @martijnboland and the rest of core team that might be a part of discussion

**Comment by Thanood** [comment] 2016-03-26 15:35
As a reminder to myself as I'm away at the moment. I also had this problem: https://github.com/aurelia/webpack-plugin/issues/9

Thanks, @hwaastad

**Comment by Thanood** [comment] 2016-04-01 14:18
As a reference for later when loading html requires is solved: https://github.com/Dogfalo/materialize/issues/2661

**Comment by Thanood** [comment] 2016-05-22 10:51
Almost there... :smile: 
https://github.com/aurelia/skeleton-navigation/pull/440#issuecomment-220825941

**Comment by Thanood** [comment] 2016-06-02 19:59
This may be helpful once above mentioned PR is merged:
https://github.com/Zevran/materialize-loader

**Comment by Thanood** [comment] 2016-06-28 09:08
continued in #195

**Closed** 2016-07-06 18:05 UTC
