### ISSUE TITLE
md-dropdown is not closed on one of its <li> items click

### ISSUE THREAD

**Issue by priceinjector** [aurelia-ui-toolkits/aurelia-materialize-bridge#395] opened 2017-03-25 18:40 UTC
It worked before updating to 0.25.0

**Comment by Thanood** [comment] 2017-03-26 16:31
@priceinjector I think it works here: https://gist.run/?id=017db322d61ed4cbc236b7fede8a18ee
This is the "Basic use" example running on 0.25.0..

Can you tell me how to reproduce that?

**Comment by priceinjector** [comment] 2017-03-26 17:37
I'm reproducing this in chrome. Maybe I did the update not correctly? When I do `npm install materialize-css --save` it brings the 0.98.1 version. Is it correct? if I set in package.json the version to be 0.98.0 it still brings the 0.98.1.
What steps should be done to update it correctly to version 0.25.0 ?
Thank you

**Comment by Thanood** [comment] 2017-03-26 17:47
Interesting, maybe 0.98.1 is the reason. The gist is still bundled with 0.98.0..
Here is what changed in 0.98.1 in Materialize dropdown: https://github.com/Dogfalo/materialize/commit/1d941102292f154fc2bd78eefb6fadf1f0649b2e

You might try to explicitly install 0.98.0 and see if it helps.
Did you try to set package.json to 0.98.0 without the `^` operator? Like this:

```js
"materialize-css": "0.98.0",
```

That should install 0.98.0..

**Comment by priceinjector** [comment] 2017-03-26 17:49
Thanks! that exactly what happened...It works now

**Comment by Thanood** [comment] 2017-03-26 19:19
I've created an issue here: https://github.com/Dogfalo/materialize/issues/4409
I will also reopen this issue to monitor it. 😃

**Comment by Thanood** [comment] 2017-03-27 07:55
> This was fixed recently in https://github.com/Dogfalo/materialize/commit/42051a56d2a35bdd8fbdffab739ee64859b186d4

✨

**Comment by mreiche** [comment] 2017-04-05 07:55
Hi Thanood. Im facing exactly the same problem here. But I don't unterstand the relationship between dogfalo/materialize, materialize-css and the bridge.

I'm using materialize-css, not dogfalo, so should I wait for a fix in materialize-css?

This bug is still present in http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/dropdown-basic-use, which library is used by the demo?

**Comment by Thanood** [comment] 2017-04-05 08:00
> I don't unterstand the relationship between dogfalo/materialize, materialize-css and the bridge

Dogfalo/materlialize and materialize-css are the same. The former is published on JSPM (vial GitHub) while the latter is published on NPM. It has a different name on NPM.

The bridge is a set of custom elements for Aurelia, using materialize (one of the above, regardless which). 😃 

> which library is used by the demo?

It is materialize-css.

I think we should wait for a fix since it's already merged but not yet published. Cannot take too long, I guess.

**Comment by mreiche** [comment] 2017-04-05 08:21
> Dogfalo/materlialize and materialize-css are the same. The former is published on JSPM (via GitHub) while the latter is published on NPM. It has a different name on NPM.

The repository may be the same, but the JSPM repository differs from the NPM repository. The JSPM repository installes only the *dist* directory from "Dogfalo/materialize", which only contains the minified code. JSPM references it in *package.json* as ```"materialize": "github:Dogfalo/materialize@^0.98.1"```

While *npm:materialize-css* is the *real* repository which contains all the sources of components and CSS. We are using this.

This was quite confusing, because I thought that JSPM:dogfalo/materialize and NPM:materialize-css are competing implementations. IMHO the documentation doesn't make this clear enough.

**Comment by Thanood** [comment] 2017-04-05 10:05
@mreiche 
I think you have good suggestions for the documentation in general.
If you want to, you can influence the docs directly by issueing a PR in this repo: https://github.com/Thanood/materialize-bridge-docs

The repo is tied to the GitBook. So if I merge a PR there, it appears in the book.
Just an idea if you want to contribute to the docs. 😃 

So, you're suggesting listing the pros and cons of each option so users know which Materialize repo to choose? I think this is a great idea! I agree.

**Closed** 2018-05-12 11:47 UTC
