### ISSUE TITLE
material_select is not a function

### ISSUE THREAD

**Issue by elsebke** [aurelia-ui-toolkits/aurelia-materialize-bridge#297] opened 2016-10-20 13:32 UTC
Aurelia version of Oct 17 with latest aurelia-materialize-bridge gives rises to error: (in chrome/IE console):
`Uncaught TypeError: $(...).material_select is not a function
createMaterialSelect @ select.js:197
(anonymous function) @ select.js:104
flushTaskQueue @ aurelia-task-queue.js:106
(anonymous function) @ aurelia-task-queue.js:75
handleFlushTimer @ aurelia-task-queue.js:33 ...`

**Comment by ad34** [comment] 2016-10-20 13:44
I m not using the bridge on my side, but I have a similar issue with aurelia + materialize. looks like a loading order  problem.

**Comment by Thanood** [comment] 2016-10-20 13:46
Which build system are you using? Aurelia-CLI, JSPM or Webpack?

**Comment by elsebke** [comment] 2016-10-28 13:02
I'm using webpack..

**Comment by Thanood** [comment] 2016-10-28 14:36
I think, @ad34 is right. This seems to be similar to #168 which is still unresolved, unfortunately..
(it begins with jspm but around https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/168#issuecomment-247151235 it's about webpack).

I'm not the most experienced webpack user and atm I'm really out of ideas. I think what happens is that because the bridge doesn't have a dependency in `materialize-css` (anymore), the two modules are not loaded in correct order. Therefore the bridge is initialized and everything is loaded before the `materlialize` scripts finish.

Because of that, the bridge calls `material_select` and it's not defined..
If you're more proficient with webpack than me, I'd be glad for any suggestions. :smiley:

**Comment by Thanood** [comment] 2016-10-28 15:00
@ad34 Are you also using webpack?

**Comment by ad34** [comment] 2016-10-31 09:19
@Thanood yes I am.

**Comment by Thanood** [comment] 2016-11-13 17:20
This **may** be resolved by putting `materialize-css` into the "bootstrap" bundle when using the webpack skeleton. The reason is: this bundle is loaded as the first bundle with the given configuration.

```javascript
bootstrap: [
    'aurelia-bootstrapper-webpack',
    'aurelia-polyfills',
    'aurelia-pal',
    'aurelia-pal-browser',
    'regenerator-runtime',
    'bluebird',
    'materialize-css'
  ],
```

This may be a conincidence, though..

**Comment by glennpierce** [comment] 2016-11-17 14:23
No that didn't work.

Although interesting that also introduces the md-waves bug where the button gets progressively darker with each click. This was after I commented import 'materialize-css'; in main.ts

**Comment by Thanood** [comment] 2016-11-17 14:37
Thanks for trying.

The dimmed buttons are actually a similar problem.
I tried to "solve" this by putting the following in `main.js` before aurelia starts:

```javascript
  if (window.Waves) {
    window.Waves.displayEffect = function() {};
  }
```

Not pretty, but it seems to work.

Honestly, global modules initializing themselves during "import" should be banned or something..
Not sure what to do, tbh.. At least I can clone your reproduction and use it as another testing ground.

I think this began when we removed the dependency on `materialize-css` from the package (but that may be a coincidence again because global modules...). I wonder if I break something if I put it back in.

**Comment by Thanood** [comment] 2016-11-17 18:53
This seems to work:
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/317#issuecomment-261288356

Without that "bootstrap" stuff above.

**Comment by Thanood** [comment] 2016-11-20 14:43
Add this to your `webpack.config.js` (right before "module.exports"):

```javascript
config.resolve.alias = {
  '$': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js'),
  'jquery': path.resolve(__dirname, 'node_modules/jquery/dist/jquery.js')
};
```

**Closed by Thanood** 2016-11-20 14:43 UTC
