### ISSUE TITLE
catalog app fails to start

### ISSUE THREAD

**Issue by adriatic** [aurelia-ui-toolkits/aurelia-materialize-bridge#78] opened 2016-02-01 23:02 UTC
@JeroenVinke 

I am not sure whether the repository is in the consistent state (if it is not, I would suggest to keep in such state :-)). Here is what happens issuing `gulp watch`
```
DEBUG [aurelia] Loading plugin http://localhost:3000/jspm_packages/npm/aurelia-templating-router@1.0.0-beta.1.1.0.
http://localhost:3000/jspm_packages/npm/aurelia-route-recognizer@1.0.0-beta.1.1.0.js Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:3000/jspm_packages/npm/aurelia-route-recognizer@1.0.0-beta.1.1.0.js(…)(anonymous function) @ :3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151
:3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:3000/jspm_packages/npm/aurelia-route-recognizer@1.0.0-beta.1.1.0.js(…)(anonymous function) @ :3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151
:3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151 Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:3000/jspm_packages/npm/aurelia-route-recognizer@1.0.0-beta.1.1.0.js(…)(anonymous function) @ :3000/jspm_packages/npm/core-js@2.0.3/modules/es6.promise.js:151
```

Given that several folks had (probably unrelated) [problems](https://gitter.im/Aurelia/Discuss?at=56afc0b66b6468374a0ad583) with current Aurelia update, I would care to understand what is happening here

**Comment by Thanood** [comment] 2016-02-02 06:06
To be honest, after that jspm-trouble I didn't care much about the sample dependencies. I have been glad that it started for me. Sorry.

Okay, let's see if I can finally understand jspm/systemjs better.. Any help appeciated. :smile: 

I've started a fresh clone now to be able to reproduce the problem, waiting for ```npm install; jspm install``` to finish.

```aurelia-route-recognizer``` is a dependency of ```aurelia-router``` as is mentioned in [config.js](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/config.js#L205). ```aurelia-router``` is a dependency of ```aurelia-bootstrapper``` [here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/master/sample/config.js#L119) which is a direct dependency of the catalog.

So both should have been pulled, right? In my filesystem, these are present. But there are also multiple versions of other dependencies (such as ```aurelia-templating```), so I don't trust my files.

I am comparing my dependencies with the kendoui-bridge. ```package.json``` is almost equal. I am missing ```aurelia-task-queue``` and of course bootstrap vs materialize.
```config.js``` has more differences. I have a lot of different versions of aurelia packages.

npm and jspm have finished on the fresh clone mentioned above. I'll have a look now.

**Comment by Thanood** [comment] 2016-02-02 06:11
Btw I've started the wrong bridge. Kendo also fails but with the following error:
```
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:3000/jspm_packages/npm/aurelia-pal-browser@1.0.0-beta.1.1.2.js
	Error loading http://localhost:3000/jspm_packages/npm/aurelia-pal-browser@1.0.0-beta.1.1.2.js as "aurelia-pal-browser" from http://localhost:3000/jspm_packages/npm/aurelia-bootstrapper@1.0.0-beta.1.1.1/aurelia-bootstrapper.js
    at o (http://localhost:3000/jspm_packages/system.js:4:13118)
    at XMLHttpRequest.s.onreadystatechange (http://localhost:3000/jspm_packages/system.js:4:13706)
```

**Comment by Thanood** [comment] 2016-02-02 06:18
The fresh clone starts up normally. :disappointed: 

Comparing dependencies to the other version (the one I have been developing with):
* package.json are not binary equal but the text is the same. Probably line endings.
* config.js as some differences - the fresh clone seems to have the correct versions

@adriatic: Is ```aurelia-route-recognizer``` present in your ```jspm_packages```?

**Comment by Thanood** [comment] 2016-02-02 06:21
This is what jspm downloaded:
![image](https://cloud.githubusercontent.com/assets/677826/12741522/6b765af4-c97d-11e5-8370-3062bfdd3691.png)

Seems like it's okay, right?
That doesn't help much finding the problem, though. :smile:

**Comment by Thanood** [comment] 2016-02-02 06:33
Not all is good. ```showdown```is undefined in AuMarkdown. I've seen that before: #19

**Comment by JeroenVinke** [comment] 2016-02-02 07:03
Lock down jspm to 0.16.15,  blow away jspm packages and reinstall. Make
sure you do this for both the plugin and the sample apl
Op 2 feb. 2016 07:33 schreef "Daniel Bendel" <notifications@github.com>:

**Comment by Thanood** [comment] 2016-02-02 07:41
That fixed the ```showdown``` problem. Now we'll have to see if it also fixes @adriatic's problem of running the catalog app as I can't reproduce the failure.

**Comment by Thanood** [comment] 2016-02-02 18:35
For reference: https://github.com/aurelia-ui-toolkits/aurelia-kendoui-bridge/issues/316

**Comment by Thanood** [comment] 2016-02-02 20:46
done here: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/commit/4f16709f48abe3adb94ef484662c39d933326256

**Comment by Thanood** [comment] 2016-02-03 07:34
Can we close this issue?

**Closed** 2016-02-28 17:43 UTC
